#!/bin/bash
set -e

# Make output directory
mkdir -p out_dir
mkdir -p html_report

#python main.py

#esta no me da autenticacion
#singularity exec docker://mnepython/mne:v1.6.1 python3 main.py


#Guiomar meg
singularity exec docker://brainlife/mne:0.23dev python3 main.py

# Mi propia imagen pero da error out of memory
#singularity exec -e docker://ghcr.io/carlota-juarez/app-mne-bids-preprocessing:latest python3 ./main.py